glazed_builder.glazed_builder_profile.*:
  type: config_entity
  label: Glazed Builder Profile
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
      label: UUID
    sidebar:
      type: boolean
      label: Sidebar
    glazed_editor:
      type: boolean
      label: Glazed Editor State
    weight:
      type: integer
      label: Weight
    roles:
      type: sequence
      label: Roles
      sequence:
        type: string
        label: Role
    elements:
      type: sequence
      label: Elements
      sequence:
        type: string
        label: Element
    blocks:
      type: sequence
      label: Blocks
      sequence:
        type: string
        label: Blocks
    views:
      type: sequence
      label: Views
      sequence:
        type: string
        label: View
    inline_buttons:
      type: sequence
      label: Inline buttons
      sequence:
        type: string
        label: Button
    modal_buttons:
      type: sequence
      label: Modal buttons
      sequence:
        type: string
        label: Button
